Math magicians: components
hunter4466/Math_magicians pull request #6
Opened 2021-08-11 04:24 UTC by hunter4466

-These points were done in this project:

*Deleted all the boilerplate from CRA.
*Created a directory called components.
*Created a new Calculator.js file inside of components directory,
*Create a React component matching calculator design.
*Used class-based components.
*Imported the component in the main component (App.js).
*Tested it in the browser and rendered it without problems.
*Fixed Linters's problems.
*Added some styling on buttons hover and click.

2021-08-11 05:58 UTC, henatan99 requested changes
Hi @hunter4466 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._
- [ ] All the boilerplate that got created by the CRA (texts, images, and styles) ought to have gotten deleted. You have some of them in your public directory. Kindly remove them. :pray: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] OPTIONAL: Your commit messages are great, but it is recommended to write them in imperative sentence form. Just take this comment as advice for the way to go in the future. It is ok for this project. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-11 05:58 UTC, henatan99 commented on src/components/calculator.js
> +export default class Calculator extends React.Component {
- [ ] OPTIONAL:  `export default class Calculator extends Component` is preferred. Also make sure to change the import code to  `import React, { Component } from 'react'` if you want to take this OPTIONAL change into consideration.

2021-08-11 05:58 UTC, henatan99 commented on src/index.js
> +    <Calculator />
- [ ] You don't need to remove the `App` component even though you have only a single child component `Calculator`. For the sake of `React/JS best practice,` you should always use the `App` component as a wrapper. Kindly brig back `App.js` and render the `Calculator` component inside it. :pray:

2021-08-11 17:43 UTC, Dipeshtwis requested changes
Hi @hunter4466, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**

-------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-11 17:43 UTC, Dipeshtwis commented on src/App.js
>    return (
- [ ] The `App.js` component should be class-based as per the project's requirements even though the functional component is very correct. Please change this functional component to a class component. :+1:
- [ ] You also need to import `React, {Component}` when you convert the functional component to class component extended from `React Component`.

2021-08-11 17:43 UTC, Dipeshtwis commented on src/components/calculator.js
> +            <button type="button" className="right-btn">+</button>
- [ ] I think it should be `÷` (division sign) instead of `+` (addition) here.

2021-08-12 00:19 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @hunter4466  🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-12 00:20 UTC, merged